version: '3.7'
services:
  alto_api:
    build:
      context: ./
      dockerfile: Dockerfile_api
    container_name: alto_api
    restart: always
    ports:
      - "80:80"
    networks:
      - network
  alto_app:
    build:
      context: ./
      dockerfile: Dockerfile_app
    container_name: alto_app
    restart: always
    ports:
      - "8080:80"
    networks:
      - network
networks:
  network:
    driver: bridge
